version: '3.9'

services:
  postgres:
    image: postgres:17.4
    container_name: etl_postgres
    environment:
      POSTGRES_DB: PrimeDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Europe/Tbilisi
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d 
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
